services:
  site:
    env_file: .env
    container_name: "${TRAEFIK_HOST}"
    restart: always
    image: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${TRAEFIK_ROUTER_NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=${TRAEFIK_PORT}"
    networks:
      - web

networks:
  web:
    external: true

