services:
  site:
    env_file: .env
    container_name: "${HOST}"
    restart: always
    image: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ROUTER_NAME}.rule=Host(`${HOST}`)"
      - "traefik.http.routers.${ROUTER_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${ROUTER_NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=${PORT}"
    networks:
      - web

networks:
  web:
    external: true

