services:
  site:
    container_name: "${HOST}"
    restart: always
    image: nginx
    expose:
      - "${PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rewrites.rule=Host(`${HOST}`)"
      - "traefik.http.routers.rewrites.entrypoints=websecure"
      - "traefik.http.routers.rewrites.tls.certresolver=letsencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=${PORT}"
    networks:
      - web

networks:
  web:
    external: true

